# -*- coding: utf-8 -*-
"""volume_of_sphere.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYpiT7ONlmIHjqURajopLoY8UQ8C654E
"""

def calculate_volume_of_sphere(radius):
  pi = 3.14
  volume = 4/3 * pi * radius * radius * radius
  return volume

radius1 = 30
area1 = calculate_volume_of_sphere(radius1)
print(f"The volume of sphere with the radius of {radius1} is: {area1}")

radius2 = 40
area2 = calculate_volume_of_sphere(radius2)
print(f"The volume of sphere with the radius of {radius2} is: {area2}")